require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe UrlCommandsController do

  # This should return the minimal set of attributes required to create a valid
  # UrlCommand. As you add validations to UrlCommand, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "model_name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # UrlCommandsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all url_commands as @url_commands" do
      url_command = UrlCommand.create! valid_attributes
      get :index, {}, valid_session
      assigns(:url_commands).should eq([url_command])
    end
  end

  describe "GET show" do
    it "assigns the requested url_command as @url_command" do
      url_command = UrlCommand.create! valid_attributes
      get :show, {:id => url_command.to_param}, valid_session
      assigns(:url_command).should eq(url_command)
    end
  end

  describe "GET new" do
    it "assigns a new url_command as @url_command" do
      get :new, {}, valid_session
      assigns(:url_command).should be_a_new(UrlCommand)
    end
  end

  describe "GET edit" do
    it "assigns the requested url_command as @url_command" do
      url_command = UrlCommand.create! valid_attributes
      get :edit, {:id => url_command.to_param}, valid_session
      assigns(:url_command).should eq(url_command)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new UrlCommand" do
        expect {
          post :create, {:url_command => valid_attributes}, valid_session
        }.to change(UrlCommand, :count).by(1)
      end

      it "assigns a newly created url_command as @url_command" do
        post :create, {:url_command => valid_attributes}, valid_session
        assigns(:url_command).should be_a(UrlCommand)
        assigns(:url_command).should be_persisted
      end

      it "redirects to the created url_command" do
        post :create, {:url_command => valid_attributes}, valid_session
        response.should redirect_to(UrlCommand.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved url_command as @url_command" do
        # Trigger the behavior that occurs when invalid params are submitted
        UrlCommand.any_instance.stub(:save).and_return(false)
        post :create, {:url_command => { "model_name" => "invalid value" }}, valid_session
        assigns(:url_command).should be_a_new(UrlCommand)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        UrlCommand.any_instance.stub(:save).and_return(false)
        post :create, {:url_command => { "model_name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested url_command" do
        url_command = UrlCommand.create! valid_attributes
        # Assuming there are no other url_commands in the database, this
        # specifies that the UrlCommand created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        UrlCommand.any_instance.should_receive(:update).with({ "model_name" => "MyString" })
        put :update, {:id => url_command.to_param, :url_command => { "model_name" => "MyString" }}, valid_session
      end

      it "assigns the requested url_command as @url_command" do
        url_command = UrlCommand.create! valid_attributes
        put :update, {:id => url_command.to_param, :url_command => valid_attributes}, valid_session
        assigns(:url_command).should eq(url_command)
      end

      it "redirects to the url_command" do
        url_command = UrlCommand.create! valid_attributes
        put :update, {:id => url_command.to_param, :url_command => valid_attributes}, valid_session
        response.should redirect_to(url_command)
      end
    end

    describe "with invalid params" do
      it "assigns the url_command as @url_command" do
        url_command = UrlCommand.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        UrlCommand.any_instance.stub(:save).and_return(false)
        put :update, {:id => url_command.to_param, :url_command => { "model_name" => "invalid value" }}, valid_session
        assigns(:url_command).should eq(url_command)
      end

      it "re-renders the 'edit' template" do
        url_command = UrlCommand.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        UrlCommand.any_instance.stub(:save).and_return(false)
        put :update, {:id => url_command.to_param, :url_command => { "model_name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested url_command" do
      url_command = UrlCommand.create! valid_attributes
      expect {
        delete :destroy, {:id => url_command.to_param}, valid_session
      }.to change(UrlCommand, :count).by(-1)
    end

    it "redirects to the url_commands list" do
      url_command = UrlCommand.create! valid_attributes
      delete :destroy, {:id => url_command.to_param}, valid_session
      response.should redirect_to(url_commands_url)
    end
  end

end
